### ISSUE TITLE
Network errors when downloading a large number of mods

### ISSUE THREAD

**Issue by linuskr** [gorilla-devs/ferium#89]
When running `ferium upgrade`, it starts with a lot of mods receiving e.g.
```
× Pick Up Notifier [Forge]                    error sending request for url (https://api.curseforge.com/v1/mods/351441/files?pageSize=10000): http2 error: stream error received: refused stream before processing any application logic
```
It's only the first n mods, and not always exactly the same number, but tends to be around n=90.

**Comment by theRookieCoder** [comment]
Yes this is a known bug. The problem happens when you have a bad internet connection or if your computer isn't powerful is thermal throttling. Does it consistently happen every time you try? Might want to reduce ye number of background apps you have open

**Comment by linuskr** [comment]
It happens consistently every time, and it should by far not be too much load for a R5 5600X.
My internet connection should be fast enough (700Mb/s), but i'll investigate if there's packet loss issues or something.

**Comment by linuskr** [comment]
Running `ferium -t 1 upgrade`, a few mods in the middle of the error block manage to connect, but it does not significantly change the result.

**Comment by theRookieCoder** [comment]
Are you using v4? I thought I fixed this in v4

**Comment by theRookieCoder** [comment]
Could you send your config file so that I can test on it?

**Comment by linuskr** [comment]
Oh god i'm so sorry, i didn't notice the new version 🤦‍♂️. I'll update and check.

**Comment by theRookieCoder** [comment]
Oh I remember now, this bugs happens when the internet connections is too fast :)

**Comment by linuskr** [comment]
Sadly, it does still happen; even adding dnsmasq as a local cache did not fix it. Is there some way to slow down the start until the dns resolver is done?

**Comment by theRookieCoder** [comment]
> Is there some way to slow down

For downloads, I implemented a permit based system where the number of tasks were limited. I though this wasn't necessary for regular requests, but looks like it is

**Comment by linuskr** [comment]
That explains why the downloads work fine ... After running it often enough and combining it with the .old folder, i think all mods are present now, but i guess the api is probably not very happy about this method.

**Comment by theRookieCoder** [comment]
Oh and could I have the number of mods you used? Just for context when implementing the semaphore

**Comment by linuskr** [comment]
I'm encountering the error down to `-t 1`, which i guess is not very helpful.

**Comment by linuskr** [comment]
Sorry, somehow i read threads, i'm using 218 mods.

**Comment by theRookieCoder** [comment]
> I'm using 218 mods

Oh yes 200+ concurrent network requests don't work very well.. hehe

**Comment by theRookieCoder** [comment]
I'm also getting tons CurseForge API authentication errors when downloading AO5

**Comment by theRookieCoder** [comment]
Oh and uhh if you don't mind, could you send your config (through email if you prefer that) so that I can test the fixes? I really don't know where to get 200+ mods from

**Comment by theRookieCoder** [comment]
Oh and uhh if you don't mind, could you send your config (through email if you prefer that) so that I can test the fixes? I really don't know where to get 200+ mods from

**Comment by KyleUltimate** [comment]
Sevtech has 253 mods
https://www.curseforge.com/minecraft/modpacks/sevtech-ages-of-the-sky

**Comment by theRookieCoder** [comment]
No I meant regular mods not modpacks. Because modpacks give version IDs but regular mods' versions need to be resolved, the requests are different

**Comment by linuskr** [comment]
Sure, no problem:
<details>
  <summary>config.json</summary>
  
  ```json
    {
  "active_profile": 0,
  "active_modpack": 0,
  "profiles": [
    {
      "name": "1.18.2",
      "output_dir": ".minecraft/mods",
      "game_version": "1.18.2",
      "mod_loader": "Forge",
      "mods": [
        {
          "name": "A Block of Charcoal",
          "identifier": {
            "CurseForgeProject": 251079
          },
          "check_mod_loader": false
        },
        {
          "name": "Absent by Design",
          "identifier": {
            "CurseForgeProject": 305840
          }
        },
        {
          "name": "Actually Compatible",
          "identifier": {
            "CurseForgeProject": 550269
          }
        },
        {
          "name": "Advancement Plaques",
          "identifier": {
            "CurseForgeProject": 499826
          }
        },
        {
          "name": "Advancement Screenshot (Forge)",
          "identifier": {
            "CurseForgeProject": 414086
          }
        },
        {
          "name": "AI Improvements",
          "identifier": {
            "CurseForgeProject": 233019
          }
        },
        {
          "name": "Akashic Tome",
          "identifier": {
            "CurseForgeProject": 250577
          }
        },
        {
          "name": "Alex's Mobs",
          "identifier": {
            "CurseForgeProject": 426558
          }
        },
        {
          "name": "AmbientSounds 5",
          "identifier": {
            "CurseForgeProject": 254284
          }
        },
        {
          "name": "Amplified Nether",
          "identifier": {
            "CurseForgeProject": 552176
          }
        },
        {
          "name": "AppleSkin",
          "identifier": {
            "CurseForgeProject": 248787
          }
        },
        {
          "name": "Archer's Paradox",
          "identifier": {
            "CurseForgeProject": 353399
          }
        },
        {
          "name": "Architectury API (Fabric/Forge)",
          "identifier": {
            "CurseForgeProject": 419699
          }
        },
        {
          "name": "Blueprint",
          "identifier": {
            "CurseForgeProject": 382216
          }
        },
        {
          "name": "Ars Nouveau",
          "identifier": {
            "CurseForgeProject": 401955
          }
        },
        {
          "name": "Artifacts",
          "identifier": {
            "CurseForgeProject": 312353
          }
        },
        {
          "name": "AttributeFix",
          "identifier": {
            "CurseForgeProject": 280510
          }
        },
        {
          "name": "Audino",
          "identifier": {
            "CurseForgeProject": 486848
          }
        },
        {
          "name": "AutoRegLib",
          "identifier": {
            "CurseForgeProject": 250363
          }
        },
        {
          "name": "Balm (Forge Edition)",
          "identifier": {
            "CurseForgeProject": 531761
          }
        },
        {
          "name": "Beautified Chat [Client] (Forge)",
          "identifier": {
            "CurseForgeProject": 514797
          }
        },
        {
          "name": "Beautified Chat [Server] (Forge)",
          "identifier": {
            "CurseForgeProject": 514796
          }
        },
        {
          "name": "Better Advancements",
          "identifier": {
            "CurseForgeProject": 272515
          }
        },
        {
          "name": "Better Animals Plus",
          "identifier": {
            "CurseForgeProject": 303557
          }
        },
        {
          "name": "Better Invisibility",
          "identifier": {
            "CurseForgeProject": 300639
          }
        },
        {
          "name": "BetterF3",
          "identifier": {
            "CurseForgeProject": 401648
          }
        },
        {
          "name": "Beyond Earth (Forge)",
          "identifier": {
            "CurseForgeProject": 377448
          }
        },
        {
          "name": "Big Brain",
          "identifier": {
            "CurseForgeProject": 421179
          }
        },
        {
          "name": "YUNG's Bridges (Forge)",
          "identifier": {
            "CurseForgeProject": 536660
          }
        },
        {
          "name": "BlockUI",
          "identifier": {
            "CurseForgeProject": 522992
          }
        },
        {
          "name": "Bouncier Beds (Forge)",
          "identifier": {
            "CurseForgeProject": 514725
          }
        },
        {
          "name": "Cable Tiers",
          "identifier": {
            "CurseForgeProject": 454382
          }
        },
        {
          "name": "Caelus API (Forge)",
          "identifier": {
            "CurseForgeProject": 308989
          }
        },
        {
          "name": "Carry On",
          "identifier": {
            "CurseForgeProject": 274259
          }
        },
        {
          "name": "Cat Herder",
          "identifier": {
            "CurseForgeProject": 580311
          }
        },
        {
          "name": "YUNG's Better Strongholds (Forge)",
          "identifier": {
            "CurseForgeProject": 465575
          }
        },
        {
          "name": "CC: Tweaked",
          "identifier": {
            "CurseForgeProject": 282001
          }
        },
        {
          "name": "Chalk",
          "identifier": {
            "CurseForgeProject": 533748
          }
        },
        {
          "name": "Chunky Pregenerator (Forge)",
          "identifier": {
            "CurseForgeProject": 485681
          }
        },
        {
          "name": "Chunk Loaders",
          "identifier": {
            "CurseForgeProject": 402924
          }
        },
        {
          "name": "Citadel",
          "identifier": {
            "CurseForgeProject": 331936
          }
        },
        {
          "name": "Client Tweaks",
          "identifier": {
            "CurseForgeProject": 251407
          }
        },
        {
          "name": "Cloth Config API (Fabric/Forge)",
          "identifier": {
            "CurseForgeProject": 348521
          }
        },
        {
          "name": "Clumps",
          "identifier": {
            "CurseForgeProject": 256717
          }
        },
        {
          "name": "CoFH Core",
          "identifier": {
            "CurseForgeProject": 69162
          }
        },
        {
          "name": "Collective (Forge)",
          "identifier": {
            "CurseForgeProject": 342584
          }
        },
        {
          "name": "Common Capabilities",
          "identifier": {
            "CurseForgeProject": 247007
          }
        },
        {
          "name": "Configured",
          "identifier": {
            "CurseForgeProject": 457570
          }
        },
        {
          "name": "Connected Glass",
          "identifier": {
            "CurseForgeProject": 383129
          }
        },
        {
          "name": "ConnectedTexturesMod",
          "identifier": {
            "CurseForgeProject": 267602
          }
        },
        {
          "name": "Connectivity[Forge/Fabric]",
          "identifier": {
            "CurseForgeProject": 470193
          }
        },
        {
          "name": "Consistency+",
          "identifier": {
            "CurseForgeProject": 430445
          }
        },
        {
          "name": "Corail Tombstone",
          "identifier": {
            "CurseForgeProject": 243707
          }
        },
        {
          "name": "Crafting Tweaks",
          "identifier": {
            "CurseForgeProject": 233071
          }
        },
        {
          "name": "Crash Utilities",
          "identifier": {
            "CurseForgeProject": 371813
          }
        },
        {
          "name": "Create",
          "identifier": {
            "CurseForgeProject": 328085
          }
        },
        {
          "name": "Create Crafts & Additions",
          "identifier": {
            "CurseForgeProject": 439890
          }
        },
        {
          "name": "Create Deco",
          "identifier": {
            "CurseForgeProject": 509285
          }
        },
        {
          "name": "Create: Alloyed",
          "identifier": {
            "CurseForgeProject": 564792
          }
        },
        {
          "name": "Create: Steam Powered",
          "identifier": {
            "CurseForgeProject": 534610
          }
        },
        {
          "name": "CreativeCore",
          "identifier": {
            "CurseForgeProject": 257814
          }
        },
        {
          "name": "Creeper Overhaul",
          "identifier": {
            "CurseForgeProject": 561625
          }
        },
        {
          "name": "Crying Ghasts (Forge)",
          "identifier": {
            "CurseForgeProject": 344360
          }
        },
        {
          "name": "Curios API (Forge)",
          "identifier": {
            "CurseForgeProject": 309927
          }
        },
        {
          "name": "Curious Elytra (Forge)",
          "identifier": {
            "CurseForgeProject": 317716
          }
        },
        {
          "name": "Cyclops Core",
          "identifier": {
            "CurseForgeProject": 232758
          }
        },
        {
          "name": "Debugify",
          "identifier": {
            "CurseForgeProject": 596224
          }
        },
        {
          "name": "Default Options",
          "identifier": {
            "CurseForgeProject": 232131
          }
        },
        {
          "name": "Diagonal Fences",
          "identifier": {
            "CurseForgeProject": 458048
          }
        },
        {
          "name": "YUNG's Better Mineshafts (Forge)",
          "identifier": {
            "CurseForgeProject": 389665
          }
        },
        {
          "name": "Domum Ornamentum",
          "identifier": {
            "CurseForgeProject": 527361
          }
        },
        {
          "name": "Dungeon Crawl",
          "identifier": {
            "CurseForgeProject": 324973
          }
        },
        {
          "name": "Dynamic View[Forge/Fabric]",
          "identifier": {
            "CurseForgeProject": 366140
          }
        },
        {
          "name": "EnderChests",
          "identifier": {
            "CurseForgeProject": 363535
          }
        },
        {
          "name": "EnderTanks",
          "identifier": {
            "CurseForgeProject": 59613
          }
        },
        {
          "name": "Ensorcellation",
          "identifier": {
            "CurseForgeProject": 349447
          }
        },
        {
          "name": "Epic Fight",
          "identifier": {
            "CurseForgeProject": 405076
          }
        },
        {
          "name": "Eroding Stone Entities (Forge)",
          "identifier": {
            "CurseForgeProject": 413431
          }
        },
        {
          "name": "ExpandAbility",
          "identifier": {
            "CurseForgeProject": 465066
          }
        },
        {
          "name": "Extra Disks",
          "identifier": {
            "CurseForgeProject": 351491
          }
        },
        {
          "name": "ExtraStorage",
          "identifier": {
            "CurseForgeProject": 410168
          }
        },
        {
          "name": "FallingTree (Forge&Fabric)",
          "identifier": {
            "CurseForgeProject": 349559
          }
        },
        {
          "name": "Farmer's Delight",
          "identifier": {
            "CurseForgeProject": 398521
          }
        },
        {
          "name": "Farming for Blockheads",
          "identifier": {
            "CurseForgeProject": 261924
          }
        },
        {
          "name": "Feature NBT Deadlock Be Gone",
          "identifier": {
            "CurseForgeProject": 560323
          }
        },
        {
          "name": "FlickerFix",
          "identifier": {
            "CurseForgeProject": 431430
          }
        },
        {
          "name": "Flywheel",
          "identifier": {
            "CurseForgeProject": 486392
          }
        },
        {
          "name": "FPS Reducer",
          "identifier": {
            "CurseForgeProject": 280294
          }
        },
        {
          "name": "Furnace Recycle (Forge)",
          "identifier": {
            "CurseForgeProject": 551140
          }
        },
        {
          "name": "Game Menu Mod Option [Forge]",
          "identifier": {
            "CurseForgeProject": 353051
          }
        },
        {
          "name": "Gauges and Switches",
          "identifier": {
            "CurseForgeProject": 296686
          }
        },
        {
          "name": "GeckoLib",
          "identifier": {
            "CurseForgeProject": 388172
          }
        },
        {
          "name": "Get It Together, Drops!",
          "identifier": {
            "CurseForgeProject": 411045
          }
        },
        {
          "name": "Giant Spawn (Forge)",
          "identifier": {
            "CurseForgeProject": 347921
          }
        },
        {
          "name": "Grindstone Sharper Tools (Forge)",
          "identifier": {
            "CurseForgeProject": 347346
          }
        },
        {
          "name": "Guard Villagers",
          "identifier": {
            "CurseForgeProject": 360203
          }
        },
        {
          "name": "Hand Over Your Items (Forge)",
          "identifier": {
            "CurseForgeProject": 450270
          }
        },
        {
          "name": "Health Overlay (Forge)",
          "identifier": {
            "CurseForgeProject": 368223
          }
        },
        {
          "name": "Iceberg",
          "identifier": {
            "CurseForgeProject": 520110
          }
        },
        {
          "name": "Inventory HUD+",
          "identifier": {
            "CurseForgeProject": 357540
          }
        },
        {
          "name": "Inventory Sorter",
          "identifier": {
            "CurseForgeProject": 240633
          }
        },
        {
          "name": "InvMove",
          "identifier": {
            "CurseForgeProject": 581854
          }
        },
        {
          "name": "InvMoveCompats",
          "identifier": {
            "CurseForgeProject": 581875
          }
        },
        {
          "name": "Iron Chests",
          "identifier": {
            "CurseForgeProject": 228756
          }
        },
        {
          "name": "Item Highlighter",
          "identifier": {
            "CurseForgeProject": 521590
          }
        },
        {
          "name": "JAMD",
          "identifier": {
            "CurseForgeProject": 422981
          }
        },
        {
          "name": "JEI Enchantment Info",
          "identifier": {
            "CurseForgeProject": 392748
          }
        },
        {
          "name": "JER Integration",
          "identifier": {
            "CurseForgeProject": 506948
          }
        },
        {
          "name": "JourneyMap",
          "identifier": {
            "CurseForgeProject": 32274
          }
        },
        {
          "name": "JourneyMap Integration",
          "identifier": {
            "CurseForgeProject": 525447
          }
        },
        {
          "name": "YUNG's API (Forge)",
          "identifier": {
            "CurseForgeProject": 421850
          }
        },
        {
          "name": "Just Enough Keys [JEK] [Forge]",
          "identifier": {
            "CurseForgeProject": 490868
          }
        },
        {
          "name": "Whisperwoods",
          "identifier": {
            "CurseForgeProject": 349597
          }
        },
        {
          "name": "Wither Skeleton Tweaks",
          "identifier": {
            "CurseForgeProject": 255902
          }
        },
        {
          "name": "Kelp Fertilizer (Forge)",
          "identifier": {
            "CurseForgeProject": 367598
          }
        },
        {
          "name": "KleeSlabs",
          "identifier": {
            "CurseForgeProject": 241895
          }
        },
        {
          "name": "Kotlin for Forge",
          "identifier": {
            "CurseForgeProject": 351264
          }
        },
        {
          "name": "Lava Clear View (Forge)",
          "identifier": {
            "CurseForgeProject": 375272
          }
        },
        {
          "name": "Lazy DataFixerUpper(LazyDFU) [FORGE]",
          "identifier": {
            "CurseForgeProject": 460819
          }
        },
        {
          "name": "Light Overlay (Rift/Forge/Fabric)",
          "identifier": {
            "CurseForgeProject": 325492
          }
        },
        {
          "name": "Little Logistics",
          "identifier": {
            "CurseForgeProject": 570050
          }
        },
        {
          "name": "Lootr (Forge)",
          "identifier": {
            "CurseForgeProject": 361276
          }
        },
        {
          "name": "Macaw's Bridges",
          "identifier": {
            "CurseForgeProject": 351725
          }
        },
        {
          "name": "Macaw's Doors",
          "identifier": {
            "CurseForgeProject": 378646
          }
        },
        {
          "name": "Macaw's Fences and Walls",
          "identifier": {
            "CurseForgeProject": 453925
          }
        },
        {
          "name": "Macaw's Furniture",
          "identifier": {
            "CurseForgeProject": 359540
          }
        },
        {
          "name": "Macaw's Lights and Lamps",
          "identifier": {
            "CurseForgeProject": 502372
          }
        },
        {
          "name": "Macaw's Paintings",
          "identifier": {
            "CurseForgeProject": 438116
          }
        },
        {
          "name": "Macaw's Roofs",
          "identifier": {
            "CurseForgeProject": 352039
          }
        },
        {
          "name": "Macaw's Trapdoors",
          "identifier": {
            "CurseForgeProject": 400933
          }
        },
        {
          "name": "Macaw's Windows",
          "identifier": {
            "CurseForgeProject": 363569
          }
        },
        {
          "name": "Magnesium/Rubidium Dynamic Lights",
          "identifier": {
            "CurseForgeProject": 551736
          }
        },
        {
          "name": "Magnesium/Rubidium Extras",
          "identifier": {
            "CurseForgeProject": 558905
          }
        },
        {
          "name": "Mantle",
          "identifier": {
            "CurseForgeProject": 74924
          }
        },
        {
          "name": "McJtyLib",
          "identifier": {
            "CurseForgeProject": 233105
          }
        },
        {
          "name": "Mekanism",
          "identifier": {
            "CurseForgeProject": 268560
          }
        },
        {
          "name": "MineColonies",
          "identifier": {
            "CurseForgeProject": 245506
          }
        },
        {
          "name": "MineColonies for ComputerCraft",
          "identifier": {
            "CurseForgeProject": 445290
          }
        },
        {
          "name": "MineMenu",
          "identifier": {
            "CurseForgeProject": 222378
          }
        },
        {
          "name": "MineTraps",
          "identifier": {
            "CurseForgeProject": 311546
          }
        },
        {
          "name": "Mod Name Tooltip",
          "identifier": {
            "CurseForgeProject": 238747
          }
        },
        {
          "name": "More Mekanism Processing",
          "identifier": {
            "CurseForgeProject": 511965
          }
        },
        {
          "name": "Morph-o-Tool",
          "identifier": {
            "CurseForgeProject": 245287
          }
        },
        {
          "name": "Mouse Tweaks",
          "identifier": {
            "CurseForgeProject": 60089
          }
        },
        {
          "name": "Moving Elevators",
          "identifier": {
            "CurseForgeProject": 373051
          }
        },
        {
          "name": "Multi-Piston",
          "identifier": {
            "CurseForgeProject": 303278
          }
        },
        {
          "name": "Neat",
          "identifier": {
            "CurseForgeProject": 238372
          }
        },
        {
          "name": "Nether's Delight",
          "identifier": {
            "CurseForgeProject": 496394
          }
        },
        {
          "name": "NetherPortalFix",
          "identifier": {
            "CurseForgeProject": 241160
          }
        },
        {
          "name": "Sound Physics Remastered",
          "identifier": {
            "CurseForgeProject": 535489
          }
        },
        {
          "name": "Not Enough Crashes (Forge)",
          "identifier": {
            "CurseForgeProject": 442354
          }
        },
        {
          "name": "Observable",
          "identifier": {
            "CurseForgeProject": 509575
          }
        },
        {
          "name": "Oculus",
          "identifier": {
            "CurseForgeProject": 581495
          }
        },
        {
          "name": "Oh The Biomes You'll Go",
          "identifier": {
            "CurseForgeProject": 247560
          }
        },
        {
          "name": "Oreberries Replanted",
          "identifier": {
            "CurseForgeProject": 454062
          }
        },
        {
          "name": "Origins (Forge)",
          "identifier": {
            "CurseForgeProject": 474438
          }
        },
        {
          "name": "Origins: Classes (Forge)",
          "identifier": {
            "CurseForgeProject": 610127
          }
        },
        {
          "name": "Paragliders",
          "identifier": {
            "CurseForgeProject": 289240
          }
        },
        {
          "name": "Patchouli",
          "identifier": {
            "CurseForgeProject": 306770
          }
        },
        {
          "name": "PerViamInvenire",
          "identifier": {
            "CurseForgeProject": 449945
          }
        },
        {
          "name": "YUNG's Better Dungeons (Forge)",
          "identifier": {
            "CurseForgeProject": 510089
          }
        },
        {
          "name": "Pick Up Notifier [Forge]",
          "identifier": {
            "CurseForgeProject": 351441
          }
        },
        {
          "name": "Placebo",
          "identifier": {
            "CurseForgeProject": 283644
          }
        },
        {
          "name": "Platforms",
          "identifier": {
            "CurseForgeProject": 244786
          }
        },
        {
          "name": "Polymorph (Forge)",
          "identifier": {
            "CurseForgeProject": 388800
          }
        },
        {
          "name": "Pretty Beaches",
          "identifier": {
            "CurseForgeProject": 290659
          }
        },
        {
          "name": "Puzzles Lib [Forge]",
          "identifier": {
            "CurseForgeProject": 495476
          }
        },
        {
          "name": "Quark",
          "identifier": {
            "CurseForgeProject": 243121
          }
        },
        {
          "name": "Quark Oddities",
          "identifier": {
            "CurseForgeProject": 301051
          }
        },
        {
          "name": "Re-chiseled",
          "identifier": {
            "CurseForgeProject": 558998
          }
        },
        {
          "name": "Realistic Bees (Forge)",
          "identifier": {
            "CurseForgeProject": 410743
          }
        },
        {
          "name": "Reborn Storage",
          "identifier": {
            "CurseForgeProject": 256662
          }
        },
        {
          "name": "Refined Storage",
          "identifier": {
            "CurseForgeProject": 243076
          }
        },
        {
          "name": "Refined Storage Addons",
          "identifier": {
            "CurseForgeProject": 272302
          }
        },
        {
          "name": "Refined Storage: Requestify",
          "identifier": {
            "CurseForgeProject": 307788
          }
        },
        {
          "name": "Repurposed Structures (Forge)",
          "identifier": {
            "CurseForgeProject": 368293
          }
        },
        {
          "name": "RFTools Base",
          "identifier": {
            "CurseForgeProject": 326041
          }
        },
        {
          "name": "RFTools Builder",
          "identifier": {
            "CurseForgeProject": 347706
          }
        },
        {
          "name": "RFTools Control",
          "identifier": {
            "CurseForgeProject": 250763
          }
        },
        {
          "name": "RFTools Dimensions",
          "identifier": {
            "CurseForgeProject": 240950
          }
        },
        {
          "name": "RFTools Power",
          "identifier": {
            "CurseForgeProject": 290209
          }
        },
        {
          "name": "RFTools Storage",
          "identifier": {
            "CurseForgeProject": 350006
          }
        },
        {
          "name": "RFTools Utility",
          "identifier": {
            "CurseForgeProject": 342466
          }
        },
        {
          "name": "Rubidium",
          "identifier": {
            "CurseForgeProject": 574856
          }
        },
        {
          "name": "Schools of Magic: Second Semester",
          "identifier": {
            "CurseForgeProject": 491624
          }
        },
        {
          "name": "Screenshot to Clipboard (Forge)",
          "identifier": {
            "CurseForgeProject": 326950
          },
          "check_game_version": false
        },
        {
          "name": "Server Tab Info",
          "identifier": {
            "CurseForgeProject": 291788
          }
        },
        {
          "name": "ShetiPhianCore",
          "identifier": {
            "CurseForgeProject": 71738
          }
        },
        {
          "name": "Shoulder Surfing Reloaded",
          "identifier": {
            "CurseForgeProject": 243190
          }
        },
        {
          "name": "Smooth Chunk Save[Forge/Fabric]",
          "identifier": {
            "CurseForgeProject": 582327
          }
        },
        {
          "name": "Snad",
          "identifier": {
            "CurseForgeProject": 241344
          }
        },
        {
          "name": "Snow Under Trees",
          "identifier": {
            "CurseForgeProject": 353942
          }
        },
        {
          "name": "Softer Hay Bales (Forge)",
          "identifier": {
            "CurseForgeProject": 344178
          }
        },
        {
          "name": "Sophisticated Backpacks",
          "identifier": {
            "CurseForgeProject": 422301
          }
        },
        {
          "name": "Sophisticated Core",
          "identifier": {
            "CurseForgeProject": 618298
          }
        },
        {
          "name": "Sophisticated Storage",
          "identifier": {
            "CurseForgeProject": 619320
          }
        },
        {
          "name": "spark",
          "identifier": {
            "CurseForgeProject": 361579
          }
        },
        {
          "name": "Stack Refill (Forge)",
          "identifier": {
            "CurseForgeProject": 411813
          }
        },
        {
          "name": "Stonecutter Recipe Tags",
          "identifier": {
            "CurseForgeProject": 548154
          }
        },
        {
          "name": "YUNG's Extras (Forge)",
          "identifier": {
            "CurseForgeProject": 480006
          }
        },
        {
          "name": "SuperMartijn642's Config Lib",
          "identifier": {
            "CurseForgeProject": 438332
          }
        },
        {
          "name": "SuperMartijn642's Core Lib",
          "identifier": {
            "CurseForgeProject": 454372
          }
        },
        {
          "name": "The One Probe",
          "identifier": {
            "CurseForgeProject": 245211
          }
        },
        {
          "name": "Tinkers Construct",
          "identifier": {
            "CurseForgeProject": 74072
          }
        },
        {
          "name": "Tinkers' Reforged",
          "identifier": {
            "CurseForgeProject": 376876
          }
        },
        {
          "name": "Too Fast",
          "identifier": {
            "CurseForgeProject": 550678
          }
        },
        {
          "name": "ToroHealth Damage Indicators",
          "identifier": {
            "CurseForgeProject": 245733
          }
        },
        {
          "name": "Trample Stopper",
          "identifier": {
            "CurseForgeProject": 297028
          }
        },
        {
          "name": "Untamed Wilds",
          "identifier": {
            "CurseForgeProject": 457252
          }
        },
        {
          "name": "Waystones",
          "identifier": {
            "CurseForgeProject": 245755
          }
        },
        {
          "name": "Weaker Spiderwebs (Forge)",
          "identifier": {
            "CurseForgeProject": 345293
          }
        },
        {
          "name": "REI Compatibility Workaround",
          "identifier": {
            "CurseForgeProject": 521393
          }
        },
        {
          "name": "Just Enough Items (JEI)",
          "identifier": {
            "CurseForgeProject": 238222
          }
        },
        {
          "name": "Just Enough Resources (JER)",
          "identifier": {
            "CurseForgeProject": 240630
          }
        },
        {
          "name": "Just Enough Professions (JEP)",
          "identifier": {
            "CurseForgeProject": 417645
          }
        },
        {
          "name": "Just Enough Advancements (JEA)",
          "identifier": {
            "CurseForgeProject": 444941
          }
        },
        {
          "name": "LibX",
          "identifier": {
            "CurseForgeProject": 412525
          }
        }
      ]
    }
  ],
  "modpacks": []
}
  ```
</details>

**Comment by theRookieCoder** [comment]
_Hopefully_ fixed by b8b272515232c0ddb76dd2d992ff79381393a207

Could you try the [actions build](https://github.com/gorilla-devs/ferium/actions/runs/2366050193) and check if it has been fixed?

**Comment by KyleUltimate** [comment]
works for me!

**Comment by linuskr** [comment]
I can confirm, it work perfectly now!

**Comment by CoolGo1425** [comment]
i know this is quite a bad necropost but this error is showing up again, and ONLY for requests for curseforge mods. when requesting mods from modrinth it works fine
